### ISSUE TITLE
Regular Crashes (Multiplayer)

### ISSUE THREAD

**Issue by saschahi** [ExterminatorX99/MagicStorageExtra#42]
getting regular client crashes on multiplayer with

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice.DrawIndexedPrimitives(PrimitiveType primitiveType, Int32 baseVertex, Int32 minVertexIndex, Int32 numVertices, Int32 startIndex, Int32 primitiveCount, IGLBuffer indices, IndexElementSize indexElementSize)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(PrimitiveType primitiveType, Int32 baseVertex, Int32 minVertexIndex, Int32 numVertices, Int32 startIndex, Int32 primitiveCount)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawPrimitives(Texture texture, Int32 baseSprite, Int32 batchSize)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.FlushBatch()
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.End()
   at Terraria.UI.GameInterfaceLayer.Draw()
   at DMD<Terraria.Main::DrawInterface>(Main , GameTime )
   at SpiritMod.SpiritDetours.DrawParticles(orig_DrawInterface orig, Main self, GameTime gameTime) in SpiritMod\SpiritDetours.cs:line 85
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)
```

I can force this crash to happen in both tModLoader 32 and 64 bit by writing fast in the search bar or scrolling fast.

my personal guess:
- Me having a 1440p Monitor (which renders more items at once in the magicstorage)
together with
- fast usage (fast scrolling or typing at high fps with frameskipping off)
crashes my due to stuff not loading/unloading fast enough

**Comment by saschahi** [comment]
why my guess is what it is:

my little brother (with his 1080p monitor and generally slower PC) never sees the same crash

**Comment by ExterminatorX99** [comment]
1. Does this happen without Spirit Mod?
2. Why do you have frame skipping turned off? Terraria is designed to run at 60fps and running at higher than that is known/expected to cause problems
