### ISSUE TITLE
game/server crash on steam host & play

### ISSUE THREAD

**Issue by sippingmariowater** [ExterminatorX99/MagicStorageExtra#67]
the game suddenly crashed while playing, which disconnected the other players. checking the server.log, it seems to be related to magic storage somehow. i was the only one using the storage at the time, and i dont believe i was actually interacting with it. i just had the window open. using 64bit version of tmodloader so i should hope its not a memory issue.

[server.log](https://github.com/ExterminatorX99/MagicStorageExtra/files/7575368/server.log)

**Comment by ExterminatorX99** [comment]
I don't see anything to indicate this was the fault of MSE

**Comment by sippingmariowater** [comment]
? the last error thrown right before the server crashed mentions MSE

> [14:48:23] [1/WARN] [tML]: Silently Caught Exception: 
System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at DMD<Terraria.NetMessage::SendData>(Int32 , Int32 , Int32 , NetworkText , Int32 , Single , Single , Single , Int32 , Int32 , Int32 )
   at MagicStorageExtra.Edits.Detours.Vanilla.NetMessage_SendData(orig_SendData orig, Int32 msgType, Int32 remoteClient, Int32 ignoreClient, NetworkText text, Int32 number, Single number2, Single number3, Single number4, Int32 number5, Int32 number6, Int32 number7) in MagicStorageExtra\Edits\Detours\Vanilla.NetMessage.cs:line 21
   at DMD<DMD<Hook<Terraria.NetMessage::SendData>?45614454>?7876905::Hook<Terraria.NetMessage::SendData>?45614454>(Int32 , Int32 , Int32 , NetworkText , Int32 , Single , Single , Single , Int32 , Int32 , Int32 )
   at Terraria.Projectile.Update(Int32 i)
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Terraria.Main.DedServ()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)

> [14:48:23] [1/WARN] [tML]: Silently Caught Exception: 
System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at DMD<Terraria.NetMessage::SendData>(Int32 , Int32 , Int32 , NetworkText , Int32 , Single , Single , Single , Int32 , Int32 , Int32 )
   at MagicStorageExtra.Edits.Detours.Vanilla.NetMessage_SendData(orig_SendData orig, Int32 msgType, Int32 remoteClient, Int32 ignoreClient, NetworkText text, Int32 number, Single number2, Single number3, Single number4, Int32 number5, Int32 number6, Int32 number7) in MagicStorageExtra\Edits\Detours\Vanilla.NetMessage.cs:line 21
   at DMD<DMD<Hook<Terraria.NetMessage::SendData>?45614454>?7876905::Hook<Terraria.NetMessage::SendData>?45614454>(Int32 , Int32 , Int32 , NetworkText , Int32 , Single , Single , Single , Int32 , Int32 , Int32 )
   at Terraria.Projectile.Update(Int32 i)
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Terraria.Main.DedServ()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)

**Comment by ExterminatorX99** [comment]
Yes, but only because MSE has a hook on NetMessage.SendData
It wasn't caused by MSE

**Comment by sippingmariowater** [comment]
hmm, alright. can you tell what else might have caused the crash? i will close this issue.

**Comment by ExterminatorX99** [comment]
On closer look, did you send the correct log? This one has no crash and has a clean shutdown.

**Comment by sippingmariowater** [comment]
yes. the game crashed right before then, i am sure of it. idk what happened ¯\_(ツ)_/¯

**Comment by ExterminatorX99** [comment]
Could you send the matching client.log file?

**Comment by sippingmariowater** [comment]
i think this might be it. 

[client.log](https://github.com/ExterminatorX99/MagicStorageExtra/files/7592175/client.log)

**Comment by ExterminatorX99** [comment]
Nope. That's the client.log the day after.
You can open the log in notepad and check the time at the start of the line and the date at the end of the first line
